### ISSUE TITLE
xenome single ended addition

### ISSUE THREAD

**Issue by syansanofi** [epam/fonda#135]
Current usage of xenome does not consider single ended reads. Proposed changes at #134

Keep in mind the package requires slightly modified naming convention for single ended reads.

Instead of
```
ambiguous_1.fastq  
ambiguous_2.fastq  
both_1.fastq 
both_2.fastq 
graft_1.fastq 
graft_2.fastq 
host_1.fastq 
host_2.fastq 
neither_1.fastq 
neither_2.fastq
```
It will be come now this  
```
ambiguous.fastq 
both.fastq 
human.fastq 
mouse.fastq 
neither.fastq
```

**Comment by kamyshova** [comment]
@syansanofi The related PR #134 is in the `develop` branch. Could we close the issue?
