### ISSUE TITLE
Feature Library duplicate samples

### ISSUE THREAD

**Issue by syansanofi** [epam/fonda#169]
In the SCRnaExpressionCellRangerFastq workflow, there are certain situations where multiplexed adt libraries (Antibody, Custom, CRISPR) can be used with individual gene expression samples. This creates a situation where single ADT will need to be used with multiplex GEX samples. This is not allowed currently and produces following error

```bash
[main] ERROR com.epam.fonda.Main - Error step in main: java.lang.IllegalArgumentException: Multiple sample types or matched controls in a sample
```

An example of the sample manifest is below:
parameterType | shortName | libtype | master
| --- | --- | --- | ---|
fastqFile | mRNA1 | GEX | mRNA1
fastqFile | mRNA2 | GEX | mRNA2
fastqFile | ADT_HTO | custom | mRNA1
fastqFile | ADT_HTO | custom | mRNA2

**Comment by kamyshova** [comment]
@syansanofi Hi, Shu.
I've created the draft [pull request](https://github.com/epam/fonda/pull/170/files) with the solution. One question is should we rely on the fact that the ADT will contain 'ADT' (case-insensitive) in its name? Or are other options possible? Alternatively, we can skip this check entirely for the SCRnaExpressionCellRangerFastq workflow.

**Comment by syansanofi** [comment]
@kamyshova Yes we can remove it. The ADT is just a string placeholder that I used. The libraries naming does not have any restrictions normally.

**Comment by kamyshova** [comment]
@syansanofi the PR was updated. Could you check this?

**Comment by kamyshova** [comment]
@syansanofi The related PR #170 is in the develop branch. Could we close the issue?

**Comment by syansanofi** [comment]
Yes, closing issue. Thank you!
