### ISSUE TITLE
RnaExpression_Fastq - SecondaryAnalysis creates blocking problems

### ISSUE THREAD

**Issue by syansanofi** [epam/fonda#193]
**Issue**  
In sync mode working in SGE, secondary analysis creates new job and submits to cluster. However this creates a blocking situation if the available open slots are exceeded by existing alignment jobs. Under this situation, the alignment jobs waits on secondaryanalysis (cufflinks or featurecount) that are in qw form.

For example:  

- Start of job
   -  available slots = 10
   - samples = 10
   - used slots = 10
- Completion of alignment, Start of secondary analysis
   - available slots = 0
   - samples = 10
   - slots needed = 10
 
@kamyshova Do you have some input on possible solutions? I am still in favor of solution proposed here: https://github.com/epam/fonda/issues/162

If not, what do you think of possible solutions?

Thanks

**Comment by sidoruka** [comment]
Hi @syansanofi, PR #180 (implementing #162) was just merged and built. Feel free to test [fonda-2.0.0.536.df6295e6b0e4b496389bda8dab34cbea715ef488.zip](https://s3.amazonaws.com/fonda-oss-builds/builds/develop/fonda-2.0.0.536.df6295e6b0e4b496389bda8dab34cbea715ef488.zip)

**Comment by syansanofi** [comment]
#180 looks good. Issue corrected. Thank you!
