### ISSUE TITLE
Preserve temporary files

### ISSUE THREAD

**Issue by syansanofi** [epam/fonda#205]
**Issue**  
Currently most of the intermediate files generated in a pipeline are deleted. Examples of these are sorted bams or unduplicated bams in DNAseq pipelines.  

To help with troubleshooting and further analysis, it would best to preserve these files.  

**Approach**  
Remove only the merged fastqs for any pipeline. Files after this stage should be preserved. Other files such as xenome removed or trimmed fastqs and later should be preserved.  For example we can remove all the files listed from being marked as tempDirs in the Star tool.

https://github.com/epam/fonda/blob/9322c5f7ddf34e7c4068b788c52c8599337f4202/src/main/java/com/epam/fonda/tools/impl/Star.java#L122-L123

**Comment by syansanofi** [comment]
@kamyshova Would this also solve #144 ? Thank you.

**Comment by kamyshova** [comment]
@syansanofi Should we preserve the temporary tool folders? For example:
`command.setTempDirs(Collections.singletonList(fusionCatcherFields.tmpFusionCatcherOutdir))`

**Comment by syansanofi** [comment]
> @syansanofi Should we preserve the temporary tool folders? For example:
> `command.setTempDirs(Collections.singletonList(fusionCatcherFields.tmpFusionCatcherOutdir))`

Yes I think they would contain files of interest like xenome output..etc
